package com.agency.crypto.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Request DTO for saving a secret message. The password is auto-generated by the service
 * and cannot be set by the creator.
 */
public class SaveMessageRequest {

  @JsonProperty("message")
  private String message;

  /** Default constructor. */
  public SaveMessageRequest() {}

  /**
   * Creates a new SaveMessageRequest with the given message.
   *
   * @param message the secret message to save
   */
  public SaveMessageRequest(String message) {
    this.message = message;
  }

  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }
}
