package com.agency.crypto.controller;

import com.agency.crypto.dto.ReceiveMessageRequest;
import com.agency.crypto.dto.ReceiveMessageResponse;
import com.agency.crypto.dto.SaveMessageRequest;
import com.agency.crypto.dto.SaveMessageResponse;
import com.agency.crypto.service.SecretMessageService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * Web controller providing REST API and serving the UI for the Secret Message Service.
 */
@Controller
public class WebController {

  private static final Logger logger = LoggerFactory.getLogger(WebController.class);

  private final SecretMessageService messageService;

  public WebController(SecretMessageService messageService) {
    this.messageService = messageService;
  }

  /**
   * Serves the main UI page.
   */
  @GetMapping("/")
  public String index() {
    return "index";
  }

  /**
   * REST endpoint to save a secret message. Password is auto-generated by the service.
   *
   * @param request the save request containing the message
   * @return the response with message ID, auto-generated password and AES key
   */
  @PostMapping("/api/save")
  @ResponseBody
  public ResponseEntity<SaveMessageResponse> saveMessage(@RequestBody SaveMessageRequest request) {
    logger.info("REST API: Save message request received");
    SaveMessageResponse response = messageService.saveMessage(request.getMessage());
    return ResponseEntity.ok(response);
  }

  /**
   * REST endpoint to receive (decrypt) a secret message.
   *
   * @param request the receive request containing ID, password, and AES key
   * @return the response with decrypted message or error
   */
  @PostMapping("/api/receive")
  @ResponseBody
  public ResponseEntity<ReceiveMessageResponse> receiveMessage(@RequestBody ReceiveMessageRequest request) {
    logger.info("REST API: Receive message request for ID: {}", request.getId());
    ReceiveMessageResponse response = messageService.receiveMessage(
        request.getId(), request.getPassword(), request.getAesKey());
    return ResponseEntity.ok(response);
  }
}
